const $=s=>document.querySelector(s), app=$('#app'), modal=$('#modal');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-GH',{style:'currency',currency:'GHS',maximumFractionDigits:2}).format(n/100);
const categories=['Household','Groceries','Fuel','Transport','Utilities','Food & dining','Health','Rent','Personal','Miscellaneous'];
const icons={Overview:'◈',Transactions:'⇄',Household:'▦',Budgets:'◴',Savings:'◇',Settings:'⚙'};
const stockAmount=i=>i.quantityLabel?.trim()||Number.isFinite(i.quantity)?(i.quantityLabel?.trim()||`${i.quantity} ${i.unit}`.trim()):i.unit||'Not specified';
let state=null,view='Overview',month=Model.today().slice(0,7),query='',status={},saving=false;
async function api(action,payload){const r=await window.planner.call(action,payload);if(r.error)throw Error(r.error);return r.data;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500);}
async function commit(next){if(saving)throw Error('Please wait for the current save.');saving=true;try{state=await api('save',next);render();}finally{saving=false;}}
function field(label,name,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(label,name,values,value){return `<label>${label}<select name="${name}" aria-label="${esc(label)}">${values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function openForm(title,body,onSubmit,submit='Save changes'){
  modal.innerHTML=`<form><div class="dialog-head"><h2>${title}</h2><button type="button" data-close class="icon-button" aria-label="Close dialog">×</button></div>${body}<p class="form-error" role="alert"></p><div class="dialog-actions"><button type="button" data-close class="secondary">Cancel</button><button type="submit" class="primary">${submit}</button></div></form>`;
  modal.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal.close());
  modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=modal.querySelector('[type=submit]');button.disabled=true;try{await onSubmit(Object.fromEntries(new FormData(e.target)));modal.close();}catch(err){modal.querySelector('.form-error').textContent=err.message;}finally{button.disabled=false;}};
  modal.showModal();
}
function amount(v){const n=Number(v);if(!Number.isFinite(n)||n<0)throw Error('Enter a valid positive amount.');return Math.round(n*100);}
function options(){return 'min="0" max="1000000000" step="0.01" required';}
function lock(){state=null;modal.close();query='';renderLock();}
async function renderLock(){
  status=await api('status');document.documentElement.dataset.theme='dark';
  app.innerHTML=`<div class="lock-page"><div class="lock-brand"><span class="brand-icon">p.</span> PocketPlan</div><div class="lock-card"><span class="eyebrow">YOUR MONEY. YOUR SPACE.</span><h1>${status.exists?'Welcome back.':'A little clarity.<br>A lot more calm.'}</h1><p>${status.exists?'Unlock your private budget planner.':'Household essentials, everyday spending, and a place for your next big goal.'}</p><form id="unlock">${field('Vault password','password','','password','required minlength="4" maxlength="1024" autocomplete="current-password"')}${!status.exists?field('Confirm password','confirm','','password','required minlength="4" autocomplete="new-password"'):''}<p class="form-error" role="alert"></p><button class="primary wide">${status.exists?'Unlock planner →':'Create my private planner →'}</button></form><div class="security-note">◇ &nbsp; Encrypted on this computer. No account needed.</div><small>Your password protects your data and backups. Keep it safe; there is no password recovery.</small></div><div class="lock-footer">Made for the everyday. And what comes next.</div></div>`;
  $('#unlock').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),b=e.target.querySelector('button');b.disabled=true;try{if(!status.exists&&f.password!==f.confirm)throw Error('Passwords do not match.');state=await api('unlock',{password:f.password,create:!status.exists});render();}catch(err){$('.form-error').textContent=err.message;}finally{b.disabled=false;}};
}
function transactionRows(entries){return entries.length?entries.map(e=>`<tr><td><span class="transaction-icon ${e.kind}">${e.kind==='expense'?'↗':'↙'}</span><span class="row-title">${esc(e.note||e.category)}<small>${esc(e.category)} · ${esc({opening:'Starting cash',savingsOpening:'Starting savings',save:'To savings',withdraw:'From savings',expense:'Expense',income:'Income'}[e.kind])}</small></span></td><td>${esc(e.date)}</td><td class="amount ${e.kind==='expense'?'':'positive'}">${['expense','save'].includes(e.kind)?'−':''}${money(e.amount)}</td><td class="actions"><button class="text-button" data-edit-entry="${e.id}">Edit</button><button class="text-button danger" data-delete-entry="${e.id}" aria-label="Delete ${esc(e.note||e.category)}">×</button></td></tr>`).join(''):`<tr><td colspan="4"><div class="empty">No transactions here yet.<small>Record spending as it happens. Every little bit counts.</small></div></td></tr>`;}
function table(entries){return `<table><thead><tr><th>TRANSACTION</th><th>DATE</th><th class="right">AMOUNT</th><th></th></tr></thead><tbody>${transactionRows(entries)}</tbody></table>`;}
function overview(){
  const t=Model.totals(state),p=Model.payday(state.settings),received=state.entries.some(e=>e.kind==='income'&&e.category==='Salary'&&e.date.startsWith(Model.today().slice(0,7))&&e.date<=Model.today());
  const needed=state.items.filter(i=>['Low stock','Out of stock'].includes(i.status));
  const spentCategories=Object.entries(t.categories).sort((a,b)=>b[1]-a[1]);
  return `<div class="hero"><div><span class="eyebrow">A CLEARER PICTURE, EVERY DAY</span><h2>Make room for what matters.</h2><p>A little planning today. More peace of mind tomorrow.</p><div class="hero-actions"><button class="primary" data-action="expense">+ Add expense</button><button class="secondary" data-action="income">Add income</button></div></div><div class="hero-art" aria-hidden="true"><div class="orbit">◇</div><span>small steps<br><b>stronger future.</b></span></div></div>
  <div class="stats"><article class="stat"><span>Available to spend <i>↗</i></span><h2>${money(t.cash)}</h2><small>Cash balance · savings kept separate</small></article><article class="stat"><span>Total saved <i>◇</i></span><h2>${money(t.savings)}</h2><small>${money(state.settings.savingsTarget)} monthly contribution goal</small></article><article class="stat"><span>Spent this month <i>◴</i></span><h2>${money(t.spent)}</h2><small>${new Date().toLocaleDateString('en-GB',{month:'long',year:'numeric'})} · recorded expenses</small></article></div>
  <div class="dashboard-grid"><section class="panel"><div class="panel-title"><h3>Your payday outlook</h3><span class="badge">${received?'Recorded':p.overdue?'Check payday':p.inWindow?'Payday window':'Upcoming'}</span></div><div class="payday-amount">${money(state.settings.salary)} <span>expected salary</span> <button class="text-button" data-action="edit-salary">Update salary</button></div><p>Usually arrives between the ${state.settings.paydayStart}${ordinal(state.settings.paydayStart)} and ${state.settings.paydayEnd}${ordinal(state.settings.paydayEnd)}.</p><div class="info-box">${received?'Salary recorded for this month. Your cash balance includes recorded income.':p.overdue?'The usual payday window has passed. If salary arrived, record it below.':`Until the ${p.end}${ordinal(p.end)}, your balance works out to <b>${money(Math.max(0,Math.floor(t.cash/p.days)))}/day</b> over ${p.days} days.`}</div><small>This is a balance split, before unrecorded bills or purchases.</small><button class="text-button spaced" data-action="salary">${received?'Record another income':'Record salary received'} →</button></section>
  <section class="panel"><div class="panel-title"><h3>Where it’s going</h3><span class="muted">This month</span></div>${spentCategories.length?spentCategories.slice(0,5).map(([c,v])=>`<div class="bar-row"><div><span>${esc(c)}</span><b>${money(v)}</b></div><progress max="${t.spent}" value="${v}"></progress></div>`).join(''):'<div class="empty"><span class="empty-symbol">◴</span>Your spending story starts here.<small>Add your first expense to see the breakdown.</small></div>'}</section>
  <section class="panel"><div class="panel-title"><h3>Recent activity</h3><button class="text-button" data-view="Transactions">View all →</button></div>${table([...state.entries].reverse().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4))}</section>
  <section class="panel"><div class="panel-title"><h3>Household check-in</h3><button class="text-button" data-view="Household">Open list →</button></div>${needed.length?needed.slice(0,4).map(i=>`<div class="stock-row"><div>${esc(i.name)}<small>${esc(stockAmount(i))}</small></div><span class="badge warning">${esc(i.status)}</span></div>`).join(''):`<div class="empty"><span class="empty-symbol">▦</span>${state.items.some(i=>i.status==='Check stock')?'Time for a quick stock check.':'Your essentials are looking good.'}<small>Track what’s available and what needs a top-up.</small></div>`}</section></div>`;
}
function ordinal(n){return n%100>=11&&n%100<=13?'th':({1:'st',2:'nd',3:'rd'}[n%10]||'th');}
function transactions(){const entries=state.entries.filter(e=>e.date.startsWith(month)&&`${e.note} ${e.category} ${e.kind}`.toLowerCase().includes(query.toLowerCase())).reverse().sort((a,b)=>b.date.localeCompare(a.date));return `<div class="toolbar"><input id="search" aria-label="Search transactions" placeholder="Search transactions…" value="${esc(query)}"><input id="month" type="month" aria-label="Transaction month" value="${month}"><button class="primary" data-action="expense">+ Add transaction</button></div><section class="panel">${table(entries)}</section><p class="footnote">Starting balances establish what you already had. Savings transfers move money between cash and savings.</p>`;}
function household(){const items=state.items.filter(i=>i.name.toLowerCase().includes(query.toLowerCase()));const needed=items.filter(i=>['Out of stock','Low stock'].includes(i.status));const cost=needed.reduce((a,i)=>a+(i.price||0)*(Number.isFinite(i.quantity)?i.quantity:0),0);return `<div class="toolbar"><input id="search" placeholder="Find an essential…" aria-label="Search household items" value="${esc(query)}"><button class="primary" data-action="item">+ Add item</button></div><div class="household-summary"><b>${state.items.length}</b> essentials tracked <span>·</span><b>${needed.length}</b> need attention <span>·</span><b>${money(Math.round(cost))}</b> estimated restock <small>Numeric quantity × unit price for low / out-of-stock items. Descriptive amounts are excluded.</small></div><section class="panel"><table><thead><tr><th>ESSENTIAL</th><th>AMOUNT / SIZE</th><th>UNIT PRICE</th><th>AVAILABILITY</th><th></th></tr></thead><tbody>${items.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(stockAmount(i))}</td><td>${i.price===null?'—':money(i.price)}</td><td><span class="badge ${['Low stock','Out of stock'].includes(i.status)?'warning':''}">${esc(i.status)}</span></td><td class="actions"><button class="text-button" data-buy="${i.id}">Buy</button><button class="text-button" data-edit-item="${i.id}">Edit</button><button class="text-button danger" data-delete-item="${i.id}" aria-label="Delete ${esc(i.name)}">×</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No essentials match. Add an item to get started.</td></tr>'}</tbody></table></section><p class="footnote">Use a number for countable items, or describe the amount in your own words. Updating stock does not change your balance; use Buy to record a purchase.</p>`;}
function budgets(){const t=Model.totals(state,month),total=Object.values(state.budgets).reduce((a,b)=>a+b,0),room=state.settings.salary-state.settings.savingsTarget-total;return `<div class="toolbar"><p>Give each part of your month a little room.</p><input type="month" id="month" aria-label="Budget month" value="${month}"></div><div class="stats"><article class="stat"><span>Monthly spending plan</span><h2>${money(total)}</h2></article><article class="stat"><span>Savings set aside in plan</span><h2>${money(state.settings.savingsTarget)}</h2></article><article class="stat"><span>${room>=0?'Unallocated income':'Over planned income'}</span><h2>${money(Math.abs(room))}</h2></article></div><div class="budget-grid">${categories.map(c=>{const limit=state.budgets[c]||0,spent=t.categories[c]||0;return `<section class="panel"><div class="panel-title"><h3>${c}</h3><button class="text-button" data-budget="${c}">${limit?'Edit':'Set limit'}</button></div><h2>${money(spent)} <small> / ${limit?money(limit):'no limit'}</small></h2><progress class="${spent>limit&&limit?'over':''}" max="${limit||1}" value="${limit?spent:0}"></progress><small>${limit?spent>limit?`${money(spent-limit)} over budget`:`${money(limit-spent)} left`:'Set a monthly limit to track this category.'}</small></section>`;}).join('')}</div><p class="footnote">Limits repeat each month. This plan reserves nothing automatically; record actual savings transfers and expenses.</p>`;}
function savings(){const t=Model.totals(state),target=state.settings.rentTarget;return `<div class="savings-hero panel"><span class="eyebrow">A HOME FOR YOUR FUTURE</span><h2>Your rent fund, one step at a time.</h2><div class="savings-number">${money(t.savings)}</div><p>Total saved · starting savings plus net transfers</p><div class="hero-actions"><button class="primary" data-action="save">+ Move money to savings</button><button class="secondary" data-action="withdraw">Withdraw to cash</button></div></div><div class="two-col"><section class="panel"><div class="panel-title"><h3>Monthly contribution</h3><button class="text-button" data-view="Settings">Edit target →</button></div><h2>${money(t.saved)} <small>of ${money(state.settings.savingsTarget)}</small></h2><progress max="${state.settings.savingsTarget||1}" value="${Math.max(0,t.saved)}"></progress><p>${money(Math.max(0,state.settings.savingsTarget-t.saved))} to go this month.</p><small>Net new transfers this month. Starting savings is separate from new contributions.</small></section><section class="panel"><div class="panel-title"><h3>Rent goal</h3><button class="text-button" data-view="Settings">Set goal →</button></div>${target?`<h2>${money(target)}</h2><progress max="${target}" value="${Math.max(0,t.savings)}"></progress><p>${money(Math.max(0,target-t.savings))} still to save.</p><small>${state.settings.savingsTarget?`${Math.ceil(Math.max(0,target-t.savings)/state.settings.savingsTarget)} monthly contributions at your current target.`:'Set a monthly savings target to estimate your timeline.'}</small>`:'<div class="empty">What amount are you working toward?<small>Set your rent target in Settings to see your progress.</small></div>'}</section></div>`;}
function settings(){return `<div class="two-col"><section class="panel"><h3>Your monthly plan</h3><form id="settings-form"><div class="form-grid">${field('Expected salary (GHS)','salary',state.settings.salary/100,'number',options())}${field('Monthly savings target (GHS)','savingsTarget',state.settings.savingsTarget/100,'number',options())}${field('Payday from (day)','paydayStart',state.settings.paydayStart,'number','min="1" max="31" required')}${field('Payday through (day)','paydayEnd',state.settings.paydayEnd,'number','min="1" max="31" required')}${field('Rent goal (GHS) · 0 to leave unset','rentTarget',state.settings.rentTarget/100,'number',options())}</div><p class="form-error" role="alert"></p><button class="primary">Save settings</button></form></section><section class="panel"><h3>Private by design</h3><p>Your SQLite database is encrypted with your password and saved on this computer.</p><div class="info-box path">${esc(status.path)}</div><p>Save an encrypted backup to an external drive or a cloud folder. You will need the password used when that backup was created.</p><div class="stack"><button class="secondary" data-action="backup">↓ Export encrypted backup</button><button class="secondary" data-action="restore">↑ Restore a backup</button><button class="secondary" data-action="lock">Lock planner</button></div><small>Restore replaces the current planner. An encrypted copy of the previous vault is kept alongside it as budget.vault.bak. No password recovery is available.</small></section></div>`;}
function render(){
  document.documentElement.dataset.theme=state.settings.theme;
  const subtitles={Overview:'A little perspective on your money.',Transactions:'The everyday details, all in one place.',Household:'Keep the essentials taken care of.',Budgets:'A thoughtful plan for the month ahead.',Savings:'Make your next chapter possible.',Settings:'Make PocketPlan feel like you.'};
  app.innerHTML=`<aside><div class="brand"><span class="brand-icon">p.</span> PocketPlan</div><span class="nav-label">YOUR PLANNER</span><nav>${Object.keys(icons).map(v=>`<button aria-label="${v}" data-view="${v}" class="${v===view?'active':''}"><span>${icons[v]}</span>${v}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="local-tag"><span class="dot"></span> Private & offline</div><button class="theme-button" data-action="theme">${state.settings.theme==='dark'?'☀ Light':'☾ Dark'} appearance</button><button aria-label="Lock planner" class="theme-button" data-action="lock">◇ Lock planner</button><div class="profile"><span>GH</span><div>My personal planner<small>Ghana cedi · GHS</small></div></div></div></aside><main><header><div><span class="eyebrow">MY PERSONAL SPACE</span><h1>${view}</h1><p>${subtitles[view]}</p></div><div class="date-pill">${new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</div></header>${({Overview:overview,Transactions:transactions,Household:household,Budgets:budgets,Savings:savings,Settings:settings}[view])()}<footer>PocketPlan <span>A little more intention. A little less worry.</span></footer></main>`;
  app.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;query='';render();});
  app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action).catch(e=>toast(e.message)));
  app.querySelectorAll('[data-edit-entry]').forEach(b=>b.onclick=()=>entryForm(state.entries.find(e=>e.id===b.dataset.editEntry)));
  app.querySelectorAll('[data-delete-entry]').forEach(b=>b.onclick=()=>remove('entries',b.dataset.deleteEntry));
  app.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>itemForm(state.items.find(i=>i.id===b.dataset.editItem)));
  app.querySelectorAll('[data-delete-item]').forEach(b=>b.onclick=()=>remove('items',b.dataset.deleteItem));
  app.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const i=state.items.find(i=>i.id===b.dataset.buy);entryForm({kind:'expense',category:'Household',note:`${i.name} (${stockAmount(i)})`,amount:i.price===null||!Number.isFinite(i.quantity)?'':Math.round(i.price*i.quantity)},i.id);});
  app.querySelectorAll('[data-budget]').forEach(b=>b.onclick=()=>openForm(`Budget · ${esc(b.dataset.budget)}`,field('Monthly limit (GHS)','limit',(state.budgets[b.dataset.budget]||0)/100,'number',options()),async f=>{const next=structuredClone(state);next.budgets[b.dataset.budget]=amount(f.limit);await commit(next);}));
  if($('#search')) $('#search').oninput=e=>{const pos=e.target.selectionStart;query=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);};
  if($('#month')) $('#month').onchange=e=>{month=e.target.value||Model.today().slice(0,7);render();};
  if($('#settings-form')) $('#settings-form').onsubmit=async e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target)),next=structuredClone(state);Object.assign(next.settings,{salary:amount(f.salary),savingsTarget:amount(f.savingsTarget),rentTarget:amount(f.rentTarget),paydayStart:Number(f.paydayStart),paydayEnd:Number(f.paydayEnd)});await commit(next);toast('Settings saved.');}catch(err){$('.form-error').textContent=err.message;}};
}
function remove(collection,id){const record=state[collection].find(e=>e.id===id);openForm('Delete this record?',`<p>${esc(record.name||record.note||record.category)}</p><p>${collection==='entries'?'Your balances will be recalculated.':'This removes the item from your household list.'}</p>`,async()=>{const next=structuredClone(state);next[collection]=next[collection].filter(e=>e.id!==id);await commit(next);},'Delete record');}
function entryForm(entry={},buyId){
  const kind=entry.kind||'expense';const kinds=['expense','income','save','withdraw',...(entry.id&&['opening','savingsOpening'].includes(kind)?[kind]:[])];
  openForm(entry.id?'Edit transaction':buyId?'Record household purchase':'Add a transaction',`<div class="form-grid">${select('Type','kind',kinds,kind)}${field('Amount (GHS)','amount',entry.amount===''?'':entry.amount!=null?entry.amount/100:'','number',options())}${field('Date','date',entry.date||Model.today(),'date',`required max="${Model.today()}"`)}${select('Category','category',[...categories,'Salary','Bonus','Savings','Opening balance'],entry.category||'Miscellaneous')}</div>${field('Description','note',entry.note||'','text','maxlength="300" placeholder="What was it for?"')}<div class="info-box">Savings transfers move money between your spending balance and savings. Income adds new money.${buyId?' Saving this purchase also marks the item available.':''}</div>`,async f=>{
    const next=structuredClone(state),record={id:entry.id||crypto.randomUUID(),kind:f.kind,amount:amount(f.amount),date:f.date,category:f.category,note:f.note.trim()};
    if(record.amount<=0)throw Error('Amount must be greater than zero.');
    if(record.date>Model.today())throw Error('Record transactions when they happen.');
    if(buyId&&record.kind!=='expense')throw Error('A household purchase must be an expense.');
    if(entry.id)next.entries=next.entries.map(e=>e.id===entry.id?record:e);else next.entries.push(record);
    const totals=Model.totals(next);if(totals.savings<0)throw Error('This would leave a negative savings balance. Check the amount.');if(record.kind==='save'&&totals.cash<0)throw Error('There is not enough available cash for this savings transfer. Record any income received first.');
    if(buyId)next.items=next.items.map(i=>i.id===buyId?{...i,status:'Available'}:i);
    await commit(next);toast('Transaction saved.');
  },'Save transaction');
}
function itemForm(item={}){openForm(item.id?'Edit essential':'Add a household essential',`${field('Item name','name',item.name||'','text','required maxlength="100" placeholder="e.g. Liquid dish soap"')}<div class="form-grid">${field('Quantity · optional','quantity',item.quantity??'','number','min="0" max="100000" step="0.01" placeholder="e.g. 2"')}${field('How much / size · optional','quantityLabel',item.quantityLabel||'','text','maxlength="100" placeholder="e.g. half cylinder, refill, one bag"')}${field('Unit · optional','unit',item.unit||'','text','maxlength="30" placeholder="bottles, rolls, kg…"')}${field('Unit price (GHS) · optional','price',item.price==null?'':item.price/100,'number','min="0" max="1000000000" step="0.01"')}${select('Availability','status',['Check stock','Available','Low stock','Out of stock'],item.status||'Check stock')}</div>`,async f=>{const next=structuredClone(state),record={id:item.id||crypto.randomUUID(),name:f.name.trim(),quantity:f.quantity===''?null:Number(f.quantity),quantityLabel:f.quantityLabel.trim(),unit:f.unit.trim(),price:f.price===''?null:amount(f.price),status:f.status};if(!record.quantityLabel&&!Number.isFinite(record.quantity)&&!record.unit)throw Error('Add a quantity, amount description, or unit.');if(item.id)next.items=next.items.map(i=>i.id===item.id?record:i);else next.items.push(record);await commit(next);});}
async function action(a){
  if(a==='theme'){const next=structuredClone(state);next.settings.theme=next.settings.theme==='dark'?'light':'dark';await commit(next);}
  else if(a==='lock'){await api('lock');lock();}
  else if(a==='item')itemForm();
  else if(a==='edit-salary')openForm('Update expected salary',`${field('Monthly salary (GHS)','salary',state.settings.salary/100,'number',options())}<div class="info-box">This updates your monthly plan. It does not add money to your balance; record salary received separately.</div>`,async f=>{const next=structuredClone(state);next.settings.salary=amount(f.salary);if(next.settings.salary<=0)throw Error('Salary must be greater than zero.');await commit(next);toast('Expected salary updated.');},'Update salary');
  else if(a==='backup'){if(await api('backup'))toast('Encrypted backup saved.');}
  else if(a==='restore')openForm('Restore an encrypted backup',`<p>This replaces your current planner. A copy of the current vault is kept as budget.vault.bak.</p>${field('Password for the backup','password','','password','required minlength="4" autocomplete="off"')}`,async f=>{const result=await api('restore',{password:f.password});if(result){state=result;render();toast('Backup restored.');}},'Choose backup & restore');
  else if(a==='salary'){
    const received=state.entries.some(e=>e.kind==='income'&&e.category==='Salary'&&e.date.startsWith(Model.today().slice(0,7)));
    entryForm({kind:'income',category:received?'Miscellaneous':'Salary',amount:received?'':state.settings.salary,note:received?'':'Monthly salary'});
  }else entryForm({kind:a,category:['save','withdraw'].includes(a)?'Savings':a==='income'?'Miscellaneous':'Household',amount:a==='save'?state.settings.savingsTarget:''});
}
window.planner.onLock(lock);
let lastActivity=Date.now();['pointerdown','keydown'].forEach(event=>document.addEventListener(event,()=>lastActivity=Date.now()));
setInterval(()=>{if(state&&Date.now()-lastActivity>10*60*1000)action('lock').catch(()=>{});},30000);
renderLock().catch(e=>{app.textContent=e.message;});


